# site settings

title: Arooran Sivakarunai
description: WOO
taglong: My Blog/Cv
tagshort: WOOOOOOOO
url: https://arooran-sivakarunai.github.io/
baseurl: ""
permalink: pretty
repo: https://github.com/Arooran-Sivakarunai/Arooran-Sivakarunai.github.io

# author settings

author:
  name: Arooran Sivakarunai
  email: arooransivakarunai@gmail.com
  photo: /assets/jpg/DITTO.png

# social media links

social:
  facebook: username
  github: Arooran-Sivakarunai
  instagram: username
  linkedin: Arooran Sivakarunai
  stackoverflow: 0000000/username
  twitter: username

# build settings

exclude:
  - LICENSE
  - README.md

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap

sass:
  sass_dir: _sass
  style: compressed
  sourcemap: never

feed:
  path: atom.xml

autopages:
  enabled: false

pagination:
  enabled: true
  per_page: 1
  sort_reverse: true
  permalink: /:num/
  title: ":title &middot; Page :num"
